name: EAS Build
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build: android, ios, or all'
        required: true
        default: 'android'

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS for Android
        if: ${{ github.event.inputs.platform == 'android' }}
        run: eas build --platform android --non-interactive --no-wait

      - name: Build on EAS for iOS
        if: ${{ github.event.inputs.platform == 'ios' }}
        run: eas build --platform ios --non-interactive --no-wait

      - name: Build on EAS for All
        if: ${{ github.event.inputs.platform == 'all' }}
        run: eas build --platform all --non-interactive --no-wait
