name: EAS Build
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build: android, ios, or all'
        required: true
        default: 'android'

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: |
          if [[ "${{ inputs.platform }}" == "all" ]]; then
            eas build --platform all --non-interactive --no-wait
          else
            eas build --platform ${{ inputs.platform }} --non-interactive --no-wait
